services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    env_file:
      - ./.env                          
    ports:
      - "5432:5432"                   
    volumes:
      - postgres_data:/var/lib/postgresql/data  

  adminer:
    image: adminer:latest
    container_name: adminer_ui
    restart: always
    ports:
      - "8080:8080"                  
    env_file:
      - ./.env                         
    environment:
      ADMINER_DEFAULT_SERVER: db  

volumes:
  postgres_data: